consumes:
  - application/json
info:
  description:  |-
    OpenAPI 2.0 documentation for [PostCage](https://github.com/trinhminhtriet/postcage).
  title: PostCage API
  contact:
    name: GitHub
    url: https://github.com/trinhminhtriet/postcage
  license:
    name: MIT license
    url: https://github.com/trinhminhtriet/postcage/blob/develop/LICENSE
  version: "v1"
paths: {}
produces:
  - application/json
schemes:
  - http
swagger: "2.0"
